CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(50) NOT NULL,
	elo INT NOT NULL DEFAULT 100,
	token VARCHAR(50) DEFAULT NULL,
	name VARCHAR(50),
	bio TEXT NULL,
	image VARCHAR(50)
);

CREATE TABLE history (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id),
    count INT NOT NULL,
    duration INT NOT NULL
);