CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(50) NOT NULL,
	elo INT DEFAULT 100,
	token VARCHAR(50) DEFAULT NULL,
	bio TEXT DEFAULT NULL,
	image VARCHAR(50) DEFAULT NULL
);