CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(50) NOT NULL,
	elo INT DEFAULT 100,
	token VARCHAR(50) DEFAULT NULL,
	name VARCHAR(50),
	bio TEXT DEFAULT NULL,
	image VARCHAR(50) DEFAULT NULL
);

CREATE TABLE history (
    id SERIAL PRIMARY KEY,
    user_id INT REFERENCES users(id),
    count INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);